development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  password:
  username:
  database:


production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  password:
  username:
  database:
